global:
  marketplace-ami: true
  owner: quickstart-eng@amazon.com
  qsname: quickstart-informatica-powercenter
  regions:
    - ap-northeast-1
    - ap-northeast-2
    - ap-south-1
    - ap-southeast-1
    - ap-southeast-2
    - eu-central-1
    - eu-west-1
    - sa-east-1
    - us-east-1
    - us-east-2
    - us-west-1
    - us-west-2
  reporting: true
tests:
  master-linux:
    parameter_input: informatica-powercenter-linux.json
    template_file: informatica-powercenter-master.template
  master-windows:
    parameter_input: informatica-powercenter-windows.json
    template_file: informatica-powercenter-master.template
